# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-gAIhTCJ8gNXvZub5rvJ2GmXo7SmuhA
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 6])
y = np.array([0, 250])

plt.plot(x, y)
plt.show()

x = np.array([0, 1, 2, 3, 4, 4.2, 4.4, 5, 6, 7, 8, 9, 10])
y = np.array([0, 0, 1, 0, 0, 2, 0, -0.5, 0, 0, 1, 0, 0])

plt.plot(x, y)
plt.show()

x = np.array([0, 1, 2, 3, 4, 4.2, 4.4, 5, 6, 7, 8, 9, 10])
y = np.array([0, 0, 1, 0, 0, 2, 0, -0.5, 0, 0, 1, 0, 0])

plt.plot(x, y, marker='o')
plt.show()

x = np.array([0, 1, 2, 3, 4, 4.2, 4.4, 5, 6, 7, 8, 9, 10])
y = np.array([0, 0, 1, 0, 0, 2, 0, -0.5, 0, 0, 1, 0, 0])

plt.plot(x, y, 'o:r')
plt.show()